#
# @(#)Makefile	1.14 97/05/06 
#

include $(XIL_CUSTOM)
include $(PROJECT_ROOT)/make/directory.cfg

SUB_DIRS= compute \
	  storage \
	  io      \
	  codec  
          

include $(PROJECT_ROOT)/make/rules/directory.cfg
