.\" @(#)xil_cis_get_random_access.3 1.1 96/09/16 SMI/VPG;
.so man3/xil.macs
.TH xil_cis_get_random_access 3 "09 June 1993" "" "XIL Library"
.SH NAME
xil_cis_get_random_access \- indicate whether a compressor supports
random accessing of a CIS 
.SH SYNOPSIS
.LP
.nf
.ft B
#include <xil/xil.h>
.LP
.sp .5v
.fi
.BI "int xil_cis_get_random_access (XilCis " cis );
.if t .in +5n
.br
.ft R
.fi
.in
.SH DESCRIPTION
.nh
.IX xil_cis_get_random_access
.IX Functions xil_cis_get_random_access
.IX "CIS Functions" "xil_cis_get_random_access"
This function returns a value that indicates whether a specified compressor supports random accessing of a compressed image sequence 
(CIS).  If random accessing
is supported, then
.BR xil_cis_seek (3)
will be able to work for backwards seeks (forward seeks are always possible).
.SH RETURN VALUES
.TP 10
TRUE
If the compressor supports random accessing of individual frames of the
sequence
.TP 10
FALSE
If the compressor does not support random accessing of a CIS 
.SH ERRORS
.nh
For a complete list of XIL error messages by number, consult Appendix B of the 
.I "XIL Programmer's Guide."
.SH EXAMPLES
.RS
.ft B
.nf 
XilCis cis;
\ ...
.sp
if(xil_cis_get_random_access(cis) == TRUE) {
	printf("backwards seeks are enabled");
}
.fi
.ft
.RE
.SH SEE ALSO
.BR xil_compress (3),
.BR xil_cis_seek (3).
