.\" @(#)xil_absolute.3 1.1 97/01/28 SMI/VPG;
.so man3/xil.macs
.TH xil_absolute 3 "04 March 1994" "" "XIL Library"
.SH NAME
xil_absolute \- find the absolute value of pixels of an image
.SH SYNOPSIS
.LP
.nf
.ft B
#include <xil/xil.h>
.LP
.sp .5v
.fi
.BI "void xil_absolute (XilImage " src , 
.if t .in +5n
.br
.BI "XilImage " dst );
.br
.ft R
.fi
.in
.SH DESCRIPTION
.nh
.IX xil_absolute
.IX Functions xil_absolute
.IX "Arithmetic and Logical Operations" "xil_absolute" 
.nh
.B xil_absolute 
(\^) performs a pixel-by-pixel abs() operation on 
.I src 
image and stores the result in the 
.I dst
(destination) image.
.P
.SH ERRORS
.nh
For a complete list of XIL error messages by number, consult Appendix B of the 
.I "XIL Programmer's Guide."
.SH EXAMPLES
Find the absolute value of pixels in
.I image1 
and store the result in 
.I dst
:
.RS
.ft B
.nf
.sp
XilImage image1, dst;
.sp
xil_absolute(image1, dst);
.sp
.fi
.ft
.RE
.SH NOTES
.LP
Source and destination images must be of the same data type and have the same number of bands.
In-place operations are supported.
