.\" @(#)xil_get_parent.3 1.2 97/05/30 SMI/VPG;
.so man3/xil.macs
.TH xil_get_parent 3 "17 August 1993" "" "XIL Library"
.SH NAME
xil_get_parent \- get a parent image
.SH SYNOPSIS
.LP
.ft B
.nf
#include <xil/xil.h>
.fi
.sp .5v
.BI "XilImage xil_get_parent ( XilImage " image );
.if t .in +5n
.br
.ft R
.fi
.in
.SH DESCRIPTION
.nh
.IX xil_get_parent
.IX Functions xil_get_parent
.IX "Image Functions" "xil_get_parent"
This function returns a handle to the parent of a child 
.I image.  
If the image is
not a child image, then 
.I NULL 
is returned.
.SH ERRORS
.nh
For a complete list of XIL error messages by number, consult Appendix B of the 
.I "XIL Programmer's Guide."
.SH EXAMPLES
Get the parent of a child image:
.LP
.nf
.sp
.RS
.ft 3
XilImage base_image, child_image;
.ta 3.5i
.sp
base_image = xil_get_parent (child_image);
.RE
.fi
.ft 1
.SH NOTES
Child images are not hierarchical.
.SH SEE ALSO
.BR xil_create_child (3)
