.\" @(#)xil_interpolation_table_get_kernel_size.3 1.1 96/09/10 SMI/VPG;
.so man3/xil.macs
.TH xil_interpolation_table_get_kernel_size 3 "03 March 1994" "" "XIL Library"
.SH NAME
xil_interpolation_table_get_kernel_size \- get the
kernel size of the subsample kernels in an interpolation table object
.SH SYNOPSIS
.ft B
.nf
#include <xil/xil.h>
.fi
.sp .5v
.BI "unsigned int xil_interpolation_table_get_kernel_size ( XilInterpolationTable "table ); 
.br
.ft R
.fi
.in
.SH DESCRIPTION
.nh
.IX xil_interpolation_table_get_kernel_size
.IX Functions xil_interpolation_table_get_kernel_size
.IX "Interpolation Table Functions" "xil_interpolation_table_get_kernel_size"
.B xil_interpolation_table_get_kernel_size
(\^) gets 
.I kernel size
from the interpolation table object
.I table.
.SH ERRORS
.nh
For a complete list of XIL error messages by number, consult Appendix B of the 
.I "XIL Programmer's Guide."
.SH EXAMPLES
Get kernel size of an interpolation table object:
.nf 
.sp
.RS
.ft 3
XilInterpolationTable table;
unsigned int kernel_size;
.sp
kernel_size = xil_interpolation_table_get_kernel_size(table);
.RE 
.fi
.ft 1
.SH SEE ALSO
.BR xil_interpolation_table_create (3),
.BR xil_interpolation_table_destroy (3),
.BR xil_interpolation_table_get_subsamples (3),
.BR xil_interpolation_table_get_data (3),
.BR xil_state_get_interpolation_tables (3).
