.\" @(#)xil_roi_subtract_rect.3 1.1 97/01/28 SMI/VPG;
.so man3/xil.macs
.TH xil_roi_subtract_rect 3 "16 June 1993" "" "XIL Library"
.SH NAME
xil_roi_subtract_rect \- subtract a rectangle from an ROI
.SH SYNOPSIS
.LP
.ft B
.nf
#include <xil/xil.h>
.fi
.sp .5v
.BI "void xil_roi_subtract_rect ( XilRoi " roi ,
.if t .in +5n
.br
.BI "long " x ,
.br
.BI "long " y ,
.br
.BI "long " width ,
.br
.BI "long " height );
.br
.ft R
.fi
.in
.SH DESCRIPTION
.IX xil_roi_subtract_rect
.IX Functions xil_roi_subtract_rect
.IX "ROI Functions" "xil_roi_subtract_rect"
.nh
This function subtracts the specified rectangle from the specified region of interest (ROI).  The coordinates of the rectangle are with respect to the storage of the image. That is, an ROI coordinate
of (0.0, 0.0) always refers to the upper left pixel in an image, regardless of the image's origin.
.SH ERRORS
.nh
For a complete list of XIL error messages by number, consult Appendix B of the 
.I "XIL Programmer's Guide."
.SH EXAMPLES
Subtract two rectangles from an ROI object, one beginning at (0,0) and ending at (34,94), the other beginning at (10,20) and ending 
at (109,69):
.LP
.nf
.sp
.RS
.ft 3
XilRoi roi;
long  xstart, ystart, width, height;   
.ta 3.5i
.sp
xstart=0; ystart=0; width=35; height=95;   
xil_roi_subtract_rect (roi, xstart, ystart, width, height);
xstart=10; ystart=20; width=100; height=50;   
xil_roi_subtract_rect (roi, xstart, ystart, width, height);
.RE
.fi
.ft 1
.SH SEE ALSO
.BR xil_get_roi (3),
.BR xil_set_roi (3),
.BR xil_roi_add_image (3),
.BR xil_roi_add_rect (3),
.BR xil_roi_add_region (3),
.BR xil_roi_create (3),
.BR xil_roi_create_copy (3),
.BR xil_roi_destroy (3),
.BR xil_roi_get_as_image (3),
.BR xil_roi_get_as_region (3),
.BR xil_roi_intersect (3),
.BR xil_roi_translate (3),
.BR xil_roi_unite (3).
