##
##  Program Name
##
PGRM=   example1

##
##  Target Object Files
##
OBJS=   fileio.o \
	window.o \
	example1.o

##
##  Additional Flags/Libraries
##
CFLAGS += -g -O
LDLIBS += -lxil -lX11
UNCOMPRESS = /usr/bin/uncompress

example1:  $(OBJS) 
	${LINK.c} $(LDFLAGS) $(OBJS) -o $@ $(LDLIBS) 

clean:
	rm -f core $(PGRM) $(OBJS)

